// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          *int32                 `protobuf:"varint,1,opt,name=code,proto3,oneof" json:"code,omitempty"`
	Msg           *string                `protobuf:"bytes,2,opt,name=msg,proto3,oneof" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResp) Reset() {
	*x = BaseResp{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResp) ProtoMessage() {}

func (x *BaseResp) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResp.ProtoReflect.Descriptor instead.
func (*BaseResp) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResp) GetCode() int32 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

func (x *BaseResp) GetMsg() string {
	if x != nil && x.Msg != nil {
		return *x.Msg
	}
	return ""
}

type AuthReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *string                `protobuf:"bytes,1,opt,name=token,proto3,oneof" json:"token,omitempty"`
	Timestamp     *int64                 `protobuf:"varint,2,opt,name=timestamp,proto3,oneof" json:"timestamp,omitempty"`
	ClientId      *uint64                `protobuf:"varint,3,opt,name=client_id,json=clientId,proto3,oneof" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthReq) Reset() {
	*x = AuthReq{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthReq) ProtoMessage() {}

func (x *AuthReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthReq.ProtoReflect.Descriptor instead.
func (*AuthReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *AuthReq) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

func (x *AuthReq) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *AuthReq) GetClientId() uint64 {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return 0
}

type AuthResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResp      *BaseResp              `protobuf:"bytes,1,opt,name=base_resp,json=baseResp,proto3,oneof" json:"base_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResp) Reset() {
	*x = AuthResp{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResp) ProtoMessage() {}

func (x *AuthResp) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResp.ProtoReflect.Descriptor instead.
func (*AuthResp) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *AuthResp) GetBaseResp() *BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type ConnectReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     *uint64                `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3,oneof" json:"channel_id,omitempty"`
	Addr          *string                `protobuf:"bytes,2,opt,name=addr,proto3,oneof" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectReq) Reset() {
	*x = ConnectReq{}
	mi := &file_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectReq) ProtoMessage() {}

func (x *ConnectReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectReq.ProtoReflect.Descriptor instead.
func (*ConnectReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectReq) GetChannelId() uint64 {
	if x != nil && x.ChannelId != nil {
		return *x.ChannelId
	}
	return 0
}

func (x *ConnectReq) GetAddr() string {
	if x != nil && x.Addr != nil {
		return *x.Addr
	}
	return ""
}

type ConnectResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResp      *BaseResp              `protobuf:"bytes,1,opt,name=base_resp,json=baseResp,proto3,oneof" json:"base_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResp) Reset() {
	*x = ConnectResp{}
	mi := &file_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResp) ProtoMessage() {}

func (x *ConnectResp) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResp.ProtoReflect.Descriptor instead.
func (*ConnectResp) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

func (x *ConnectResp) GetBaseResp() *BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type ClientCloseReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientCloseReq) Reset() {
	*x = ClientCloseReq{}
	mi := &file_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientCloseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientCloseReq) ProtoMessage() {}

func (x *ClientCloseReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientCloseReq.ProtoReflect.Descriptor instead.
func (*ClientCloseReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{5}
}

type ClientCloseResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResp      *BaseResp              `protobuf:"bytes,1,opt,name=base_resp,json=baseResp,proto3,oneof" json:"base_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientCloseResp) Reset() {
	*x = ClientCloseResp{}
	mi := &file_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientCloseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientCloseResp) ProtoMessage() {}

func (x *ClientCloseResp) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientCloseResp.ProtoReflect.Descriptor instead.
func (*ClientCloseResp) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{6}
}

func (x *ClientCloseResp) GetBaseResp() *BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type ChannelCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     *uint64                `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3,oneof" json:"channel_id,omitempty"`
	WindowSize    *uint64                `protobuf:"varint,3,opt,name=window_size,json=windowSize,proto3,oneof" json:"window_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelCreateReq) Reset() {
	*x = ChannelCreateReq{}
	mi := &file_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelCreateReq) ProtoMessage() {}

func (x *ChannelCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelCreateReq.ProtoReflect.Descriptor instead.
func (*ChannelCreateReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{7}
}

func (x *ChannelCreateReq) GetChannelId() uint64 {
	if x != nil && x.ChannelId != nil {
		return *x.ChannelId
	}
	return 0
}

func (x *ChannelCreateReq) GetWindowSize() uint64 {
	if x != nil && x.WindowSize != nil {
		return *x.WindowSize
	}
	return 0
}

type ChannelCreateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResp      *BaseResp              `protobuf:"bytes,1,opt,name=base_resp,json=baseResp,proto3,oneof" json:"base_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelCreateResp) Reset() {
	*x = ChannelCreateResp{}
	mi := &file_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelCreateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelCreateResp) ProtoMessage() {}

func (x *ChannelCreateResp) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelCreateResp.ProtoReflect.Descriptor instead.
func (*ChannelCreateResp) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{8}
}

func (x *ChannelCreateResp) GetBaseResp() *BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type ChannelCloseNoti struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     *uint64                `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3,oneof" json:"channel_id,omitempty"`
	Msg           *string                `protobuf:"bytes,2,opt,name=msg,proto3,oneof" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelCloseNoti) Reset() {
	*x = ChannelCloseNoti{}
	mi := &file_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelCloseNoti) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelCloseNoti) ProtoMessage() {}

func (x *ChannelCloseNoti) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelCloseNoti.ProtoReflect.Descriptor instead.
func (*ChannelCloseNoti) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{9}
}

func (x *ChannelCloseNoti) GetChannelId() uint64 {
	if x != nil && x.ChannelId != nil {
		return *x.ChannelId
	}
	return 0
}

func (x *ChannelCloseNoti) GetMsg() string {
	if x != nil && x.Msg != nil {
		return *x.Msg
	}
	return ""
}

type DataNoti struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     *uint64                `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3,oneof" json:"channel_id,omitempty"`
	Code          *uint32                `protobuf:"varint,2,opt,name=code,proto3,oneof" json:"code,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3,oneof" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataNoti) Reset() {
	*x = DataNoti{}
	mi := &file_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataNoti) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataNoti) ProtoMessage() {}

func (x *DataNoti) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataNoti.ProtoReflect.Descriptor instead.
func (*DataNoti) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{10}
}

func (x *DataNoti) GetChannelId() uint64 {
	if x != nil && x.ChannelId != nil {
		return *x.ChannelId
	}
	return 0
}

func (x *DataNoti) GetCode() uint32 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

func (x *DataNoti) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ChannelWindowUpdateNoti struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     *uint64                `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3,oneof" json:"channel_id,omitempty"`
	Code          *uint32                `protobuf:"varint,2,opt,name=code,proto3,oneof" json:"code,omitempty"`
	WindowSize    *uint64                `protobuf:"varint,3,opt,name=window_size,json=windowSize,proto3,oneof" json:"window_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelWindowUpdateNoti) Reset() {
	*x = ChannelWindowUpdateNoti{}
	mi := &file_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelWindowUpdateNoti) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelWindowUpdateNoti) ProtoMessage() {}

func (x *ChannelWindowUpdateNoti) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelWindowUpdateNoti.ProtoReflect.Descriptor instead.
func (*ChannelWindowUpdateNoti) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{11}
}

func (x *ChannelWindowUpdateNoti) GetChannelId() uint64 {
	if x != nil && x.ChannelId != nil {
		return *x.ChannelId
	}
	return 0
}

func (x *ChannelWindowUpdateNoti) GetCode() uint32 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

func (x *ChannelWindowUpdateNoti) GetWindowSize() uint64 {
	if x != nil && x.WindowSize != nil {
		return *x.WindowSize
	}
	return 0
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\"K\n" +
	"\bBaseResp\x12\x17\n" +
	"\x04code\x18\x01 \x01(\x05H\x00R\x04code\x88\x01\x01\x12\x15\n" +
	"\x03msg\x18\x02 \x01(\tH\x01R\x03msg\x88\x01\x01B\a\n" +
	"\x05_codeB\x06\n" +
	"\x04_msg\"\x8f\x01\n" +
	"\aAuthReq\x12\x19\n" +
	"\x05token\x18\x01 \x01(\tH\x00R\x05token\x88\x01\x01\x12!\n" +
	"\ttimestamp\x18\x02 \x01(\x03H\x01R\ttimestamp\x88\x01\x01\x12 \n" +
	"\tclient_id\x18\x03 \x01(\x04H\x02R\bclientId\x88\x01\x01B\b\n" +
	"\x06_tokenB\f\n" +
	"\n" +
	"_timestampB\f\n" +
	"\n" +
	"_client_id\"E\n" +
	"\bAuthResp\x12+\n" +
	"\tbase_resp\x18\x01 \x01(\v2\t.BaseRespH\x00R\bbaseResp\x88\x01\x01B\f\n" +
	"\n" +
	"_base_resp\"a\n" +
	"\n" +
	"ConnectReq\x12\"\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\x04H\x00R\tchannelId\x88\x01\x01\x12\x17\n" +
	"\x04addr\x18\x02 \x01(\tH\x01R\x04addr\x88\x01\x01B\r\n" +
	"\v_channel_idB\a\n" +
	"\x05_addr\"H\n" +
	"\vConnectResp\x12+\n" +
	"\tbase_resp\x18\x01 \x01(\v2\t.BaseRespH\x00R\bbaseResp\x88\x01\x01B\f\n" +
	"\n" +
	"_base_resp\"\x10\n" +
	"\x0eClientCloseReq\"L\n" +
	"\x0fClientCloseResp\x12+\n" +
	"\tbase_resp\x18\x01 \x01(\v2\t.BaseRespH\x00R\bbaseResp\x88\x01\x01B\f\n" +
	"\n" +
	"_base_resp\"{\n" +
	"\x10ChannelCreateReq\x12\"\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\x04H\x00R\tchannelId\x88\x01\x01\x12$\n" +
	"\vwindow_size\x18\x03 \x01(\x04H\x01R\n" +
	"windowSize\x88\x01\x01B\r\n" +
	"\v_channel_idB\x0e\n" +
	"\f_window_size\"N\n" +
	"\x11ChannelCreateResp\x12+\n" +
	"\tbase_resp\x18\x01 \x01(\v2\t.BaseRespH\x00R\bbaseResp\x88\x01\x01B\f\n" +
	"\n" +
	"_base_resp\"d\n" +
	"\x10ChannelCloseNoti\x12\"\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\x04H\x00R\tchannelId\x88\x01\x01\x12\x15\n" +
	"\x03msg\x18\x02 \x01(\tH\x01R\x03msg\x88\x01\x01B\r\n" +
	"\v_channel_idB\x06\n" +
	"\x04_msg\"\x81\x01\n" +
	"\bDataNoti\x12\"\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\x04H\x00R\tchannelId\x88\x01\x01\x12\x17\n" +
	"\x04code\x18\x02 \x01(\rH\x01R\x04code\x88\x01\x01\x12\x17\n" +
	"\x04data\x18\x03 \x01(\fH\x02R\x04data\x88\x01\x01B\r\n" +
	"\v_channel_idB\a\n" +
	"\x05_codeB\a\n" +
	"\x05_data\"\xa4\x01\n" +
	"\x17ChannelWindowUpdateNoti\x12\"\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\x04H\x00R\tchannelId\x88\x01\x01\x12\x17\n" +
	"\x04code\x18\x02 \x01(\rH\x01R\x04code\x88\x01\x01\x12$\n" +
	"\vwindow_size\x18\x03 \x01(\x04H\x02R\n" +
	"windowSize\x88\x01\x01B\r\n" +
	"\v_channel_idB\a\n" +
	"\x05_codeB\x0e\n" +
	"\f_window_sizeB\x06Z\x04./pbb\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_message_proto_goTypes = []any{
	(*BaseResp)(nil),                // 0: BaseResp
	(*AuthReq)(nil),                 // 1: AuthReq
	(*AuthResp)(nil),                // 2: AuthResp
	(*ConnectReq)(nil),              // 3: ConnectReq
	(*ConnectResp)(nil),             // 4: ConnectResp
	(*ClientCloseReq)(nil),          // 5: ClientCloseReq
	(*ClientCloseResp)(nil),         // 6: ClientCloseResp
	(*ChannelCreateReq)(nil),        // 7: ChannelCreateReq
	(*ChannelCreateResp)(nil),       // 8: ChannelCreateResp
	(*ChannelCloseNoti)(nil),        // 9: ChannelCloseNoti
	(*DataNoti)(nil),                // 10: DataNoti
	(*ChannelWindowUpdateNoti)(nil), // 11: ChannelWindowUpdateNoti
}
var file_message_proto_depIdxs = []int32{
	0, // 0: AuthResp.base_resp:type_name -> BaseResp
	0, // 1: ConnectResp.base_resp:type_name -> BaseResp
	0, // 2: ClientCloseResp.base_resp:type_name -> BaseResp
	0, // 3: ChannelCreateResp.base_resp:type_name -> BaseResp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	file_message_proto_msgTypes[0].OneofWrappers = []any{}
	file_message_proto_msgTypes[1].OneofWrappers = []any{}
	file_message_proto_msgTypes[2].OneofWrappers = []any{}
	file_message_proto_msgTypes[3].OneofWrappers = []any{}
	file_message_proto_msgTypes[4].OneofWrappers = []any{}
	file_message_proto_msgTypes[6].OneofWrappers = []any{}
	file_message_proto_msgTypes[7].OneofWrappers = []any{}
	file_message_proto_msgTypes[8].OneofWrappers = []any{}
	file_message_proto_msgTypes[9].OneofWrappers = []any{}
	file_message_proto_msgTypes[10].OneofWrappers = []any{}
	file_message_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
